/** Expanded majors list modeled on Texas A&M University catalog breadth. */

export const TEXAS_AM_MAJORS = [
  "Accounting",
  "Aerospace Engineering",
  "Agribusiness",
  "Agricultural Communications",
  "Agricultural Economics",
  "Agricultural Leadership",
  "Agricultural Science",
  "Agricultural Systems Management",
  "Agronomy",
  "Animal Science",
  "Anthropology",
  "Applied Mathematical Sciences",
  "Architecture",
  "Art",
  "Biochemistry",
  "Bioenvironmental Sciences",
  "Biological & Agricultural Engineering",
  "Biology",
  "Biomedical Engineering",
  "Biomedical Sciences",
  "Biotechnology",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Classical Studies",
  "Communication",
  "Community Health",
  "Computer Engineering",
  "Computer Science",
  "Construction Science",
  "Criminal Justice",
  "Dance Science",
  "Data Engineering",
  "Data Science",
  "Economics",
  "Electrical Engineering",
  "Electronic Systems Engineering Technology",
  "English",
  "Entomology",
  "Environmental Design",
  "Environmental Engineering",
  "Environmental Geosciences",
  "Environmental Studies",
  "Finance",
  "Food Science & Technology",
  "Forestry",
  "French",
  "Geography",
  "Geology",
  "Geophysics",
  "German",
  "Graphic Design",
  "Health",
  "History",
  "Horticulture",
  "Human Development & Family Sciences",
  "Human Resource Development",
  "Industrial Distribution",
  "Industrial Engineering",
  "Information Technology Service Management",
  "Interdisciplinary Studies",
  "International Studies",
  "Journalism",
  "Kinesiology",
  "Landscape Architecture",
  "Management",
  "Management Information Systems",
  "Marine Biology",
  "Marine Engineering Technology",
  "Maritime Administration",
  "Marketing",
  "Materials Science & Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Meteorology",
  "Microbiology",
  "Military Science",
  "Multidisciplinary Engineering Technology",
  "Music",
  "Neuroscience",
  "Nuclear Engineering",
  "Nursing",
  "Nutrition",
  "Ocean Engineering",
  "Petroleum Engineering",
  "Philosophy",
  "Physics",
  "Plant & Environmental Soil Science",
  "Political Science",
  "Poultry Science",
  "Psychology",
  "Public Health",
  "Public Relations",
  "Rangeland Ecology & Management",
  "Recreation, Park & Tourism Sciences",
  "Religious Studies",
  "Renewable Natural Resources",
  "Russian",
  "Social Work",
  "Sociology",
  "Spanish",
  "Sport Management",
  "Statistics",
  "Supply Chain Management",
  "Telecommunication & Media Studies",
  "Tourism & Hospitality Management",
  "University Studies",
  "Urban & Regional Planning",
  "Visualization",
  "Wildlife & Fisheries Sciences",
  "Women's & Gender Studies",
  "Zoology",
] as const;
