export interface UniversityPreset {
  id: string;
  name: string;
  shortName: string;
  primary: string;
  secondary: string;
}

/** U.S. universities — brand-inspired colors (campus theme for SportsOS / ClubOS; accents for Greek). */
export const UNIVERSITY_PRESETS: UniversityPreset[] = [
  { id: "alabama", name: "University of Alabama", shortName: "Alabama", primary: "#9E1B32", secondary: "#828A8F" },
  { id: "arizona", name: "University of Arizona", shortName: "Arizona", primary: "#AB0520", secondary: "#0C234B" },
  { id: "arizona-state", name: "Arizona State University", shortName: "ASU", primary: "#8C1D40", secondary: "#FFC627" },
  { id: "auburn", name: "Auburn University", shortName: "Auburn", primary: "#0C2340", secondary: "#E87722" },
  { id: "berkeley", name: "UC Berkeley", shortName: "Cal", primary: "#003262", secondary: "#FDB515" },
  { id: "boston-college", name: "Boston College", shortName: "BC", primary: "#8B0000", secondary: "#B8860B" },
  { id: "boston-u", name: "Boston University", shortName: "BU", primary: "#CC0000", secondary: "#FFFFFF" },
  { id: "byu", name: "Brigham Young University", shortName: "BYU", primary: "#002E5D", secondary: "#FFFFFF" },
  { id: "clemson", name: "Clemson University", shortName: "Clemson", primary: "#F56600", secondary: "#522D80" },
  { id: "colorado", name: "University of Colorado Boulder", shortName: "Colorado", primary: "#CFB87C", secondary: "#000000" },
  { id: "columbia", name: "Columbia University", shortName: "Columbia", primary: "#003DA5", secondary: "#FFFFFF" },
  { id: "cornell", name: "Cornell University", shortName: "Cornell", primary: "#B31B1B", secondary: "#FFFFFF" },
  { id: "dartmouth", name: "Dartmouth College", shortName: "Dartmouth", primary: "#00693E", secondary: "#FFFFFF" },
  { id: "duke", name: "Duke University", shortName: "Duke", primary: "#003087", secondary: "#FFFFFF" },
  { id: "florida", name: "University of Florida", shortName: "Florida", primary: "#0021A5", secondary: "#FA4616" },
  { id: "florida-state", name: "Florida State University", shortName: "FSU", primary: "#782F40", secondary: "#CEB888" },
  { id: "georgetown", name: "Georgetown University", shortName: "Georgetown", primary: "#041E42", secondary: "#8D817B" },
  { id: "georgia", name: "University of Georgia", shortName: "UGA", primary: "#BA0C2F", secondary: "#000000" },
  { id: "georgia-tech", name: "Georgia Institute of Technology", shortName: "Georgia Tech", primary: "#B3A369", secondary: "#003057" },
  { id: "harvard", name: "Harvard University", shortName: "Harvard", primary: "#A51C30", secondary: "#1E1E1E" },
  { id: "illinois", name: "University of Illinois Urbana-Champaign", shortName: "Illinois", primary: "#13294B", secondary: "#E84A27" },
  { id: "indiana", name: "Indiana University Bloomington", shortName: "Indiana", primary: "#990000", secondary: "#FFFFFF" },
  { id: "iowa", name: "University of Iowa", shortName: "Iowa", primary: "#FFCD00", secondary: "#000000" },
  { id: "kansas", name: "University of Kansas", shortName: "Kansas", primary: "#0051BA", secondary: "#E8000D" },
  { id: "kentucky", name: "University of Kentucky", shortName: "Kentucky", primary: "#0033A0", secondary: "#FFFFFF" },
  { id: "lsu", name: "Louisiana State University", shortName: "LSU", primary: "#461D7C", secondary: "#FDD023" },
  { id: "maryland", name: "University of Maryland", shortName: "Maryland", primary: "#E03A3E", secondary: "#FFD520" },
  { id: "miami", name: "University of Miami", shortName: "Miami", primary: "#F47321", secondary: "#005030" },
  { id: "michigan", name: "University of Michigan", shortName: "Michigan", primary: "#00274C", secondary: "#FFCB05" },
  { id: "michigan-state", name: "Michigan State University", shortName: "MSU", primary: "#18453B", secondary: "#FFFFFF" },
  { id: "minnesota", name: "University of Minnesota", shortName: "Minnesota", primary: "#7A0019", secondary: "#FFCC33" },
  { id: "missouri", name: "University of Missouri", shortName: "Mizzou", primary: "#F1B82D", secondary: "#000000" },
  { id: "north-carolina", name: "UNC Chapel Hill", shortName: "UNC", primary: "#7BAFD4", secondary: "#13294B" },
  { id: "northwestern", name: "Northwestern University", shortName: "Northwestern", primary: "#4E2A84", secondary: "#FFFFFF" },
  { id: "notre-dame", name: "University of Notre Dame", shortName: "Notre Dame", primary: "#0C2340", secondary: "#C99700" },
  { id: "ohio-state", name: "The Ohio State University", shortName: "Ohio State", primary: "#BB0000", secondary: "#666666" },
  { id: "oklahoma", name: "University of Oklahoma", shortName: "Oklahoma", primary: "#841617", secondary: "#FDF9D8" },
  { id: "oregon", name: "University of Oregon", shortName: "Oregon", primary: "#154733", secondary: "#FEE123" },
  { id: "penn", name: "University of Pennsylvania", shortName: "Penn", primary: "#011F5B", secondary: "#990000" },
  { id: "penn-state", name: "Penn State University", shortName: "Penn State", primary: "#041E42", secondary: "#FFFFFF" },
  { id: "pitt", name: "University of Pittsburgh", shortName: "Pitt", primary: "#003594", secondary: "#FFB81C" },
  { id: "princeton", name: "Princeton University", shortName: "Princeton", primary: "#E77500", secondary: "#000000" },
  { id: "purdue", name: "Purdue University", shortName: "Purdue", primary: "#CEB888", secondary: "#000000" },
  { id: "rutgers", name: "Rutgers University", shortName: "Rutgers", primary: "#CC0033", secondary: "#5F6A72" },
  { id: "south-carolina", name: "University of South Carolina", shortName: "South Carolina", primary: "#73000A", secondary: "#000000" },
  { id: "stanford", name: "Stanford University", shortName: "Stanford", primary: "#8C1515", secondary: "#2E2D29" },
  { id: "syracuse", name: "Syracuse University", shortName: "Syracuse", primary: "#F76900", secondary: "#002D72" },
  { id: "tennessee", name: "University of Tennessee", shortName: "Tennessee", primary: "#FF8200", secondary: "#FFFFFF" },
  { id: "texas", name: "University of Texas at Austin", shortName: "Texas", primary: "#BF5700", secondary: "#FFFFFF" },
  { id: "texas-am", name: "Texas A&M University", shortName: "Texas A&M", primary: "#500000", secondary: "#FFFFFF" },
  { id: "ucla", name: "UCLA", shortName: "UCLA", primary: "#2774AE", secondary: "#FFD100" },
  { id: "usc", name: "University of Southern California", shortName: "USC", primary: "#990000", secondary: "#FFCC00" },
  { id: "virginia", name: "University of Virginia", shortName: "UVA", primary: "#232D4B", secondary: "#F84C1E" },
  { id: "virginia-tech", name: "Virginia Tech", shortName: "Virginia Tech", primary: "#861F41", secondary: "#E87722" },
  { id: "washington", name: "University of Washington", shortName: "Washington", primary: "#4B2E83", secondary: "#B7A57A" },
  { id: "wisconsin", name: "University of Wisconsin-Madison", shortName: "Wisconsin", primary: "#C5050C", secondary: "#FFFFFF" },
  { id: "yale", name: "Yale University", shortName: "Yale", primary: "#00356B", secondary: "#FFFFFF" },
  { id: "vanderbilt", name: "Vanderbilt University", shortName: "Vanderbilt", primary: "#866D4B", secondary: "#000000" },
  { id: "wake-forest", name: "Wake Forest University", shortName: "Wake Forest", primary: "#9E7B0D", secondary: "#000000" },
  { id: "texas-tech", name: "Texas Tech University", shortName: "Texas Tech", primary: "#CC0000", secondary: "#000000" },
  { id: "west-virginia", name: "West Virginia University", shortName: "WVU", primary: "#002855", secondary: "#EAAA00" },
  { id: "nebraska", name: "University of Nebraska–Lincoln", shortName: "Nebraska", primary: "#E41C38", secondary: "#FDF2D9" },
  { id: "oklahoma-state", name: "Oklahoma State University", shortName: "Oklahoma State", primary: "#FF7300", secondary: "#000000" },
  { id: "baylor", name: "Baylor University", shortName: "Baylor", primary: "#154734", secondary: "#FFB81C" },
  { id: "tcu", name: "Texas Christian University", shortName: "TCU", primary: "#4D1979", secondary: "#A2AAAD" },
  { id: "houston", name: "University of Houston", shortName: "Houston", primary: "#C8102E", secondary: "#FFFFFF" },
  { id: "smu", name: "Southern Methodist University", shortName: "SMU", primary: "#CC0035", secondary: "#354CA1" },
  { id: "rice", name: "Rice University", shortName: "Rice", primary: "#00205B", secondary: "#FFFFFF" },
  { id: "ucf", name: "University of Central Florida", shortName: "UCF", primary: "#BA9B37", secondary: "#000000" },
  { id: "usf", name: "University of South Florida", shortName: "USF", primary: "#006747", secondary: "#CFC493" },
  { id: "uc-davis", name: "UC Davis", shortName: "UC Davis", primary: "#002855", secondary: "#C99700" },
  { id: "uc-san-diego", name: "UC San Diego", shortName: "UCSD", primary: "#182B49", secondary: "#FFCD00" },
  { id: "uc-irvine", name: "UC Irvine", shortName: "UCI", primary: "#0064A4", secondary: "#FFD200" },
  { id: "uc-santa-barbara", name: "UC Santa Barbara", shortName: "UCSB", primary: "#003660", secondary: "#FEBC11" },
  { id: "uc-riverside", name: "UC Riverside", shortName: "UCR", primary: "#003DA5", secondary: "#FFD200" },
  { id: "san-diego-state", name: "San Diego State University", shortName: "SDSU", primary: "#A6192E", secondary: "#000000" },
  { id: "fresno-state", name: "California State University, Fresno", shortName: "Fresno State", primary: "#DB0032", secondary: "#002F6C" },
  { id: "boise-state", name: "Boise State University", shortName: "Boise State", primary: "#0033A0", secondary: "#D64309" },
  { id: "utah", name: "University of Utah", shortName: "Utah", primary: "#CC0000", secondary: "#FFFFFF" },
  { id: "utah-state", name: "Utah State University", shortName: "Utah State", primary: "#00263A", secondary: "#FFFFFF" },
  { id: "colorado-state", name: "Colorado State University", shortName: "Colorado State", primary: "#1E4D2B", secondary: "#C8C372" },
  { id: "air-force", name: "U.S. Air Force Academy", shortName: "Air Force", primary: "#003087", secondary: "#8A8D8F" },
  { id: "army", name: "U.S. Military Academy (Army)", shortName: "Army", primary: "#000000", secondary: "#B9975B" },
  { id: "navy", name: "U.S. Naval Academy", shortName: "Navy", primary: "#00205B", secondary: "#C5B783" },
  { id: "cincinnati", name: "University of Cincinnati", shortName: "Cincinnati", primary: "#E00122", secondary: "#000000" },
  { id: "louisville", name: "University of Louisville", shortName: "Louisville", primary: "#AD0000", secondary: "#000000" },
  { id: "memphis", name: "University of Memphis", shortName: "Memphis", primary: "#003087", secondary: "#8A8D8F" },
  { id: "arkansas", name: "University of Arkansas", shortName: "Arkansas", primary: "#9D2235", secondary: "#FFFFFF" },
  { id: "mississippi", name: "University of Mississippi", shortName: "Ole Miss", primary: "#CE1126", secondary: "#14213D" },
  { id: "mississippi-state", name: "Mississippi State University", shortName: "Miss State", primary: "#5D1725", secondary: "#FFFFFF" },
  { id: "auburn-montgomery", name: "Auburn University at Montgomery", shortName: "AUM", primary: "#0C2340", secondary: "#E87722" },
  { id: "tulane", name: "Tulane University", shortName: "Tulane", primary: "#006747", secondary: "#87CEEB" },
  { id: "north-texas", name: "University of North Texas", shortName: "UNT", primary: "#00853E", secondary: "#000000" },
  { id: "utsa", name: "UT San Antonio", shortName: "UTSA", primary: "#0C2340", secondary: "#F15A22" },
  { id: "utep", name: "UT El Paso", shortName: "UTEP", primary: "#FF8200", secondary: "#041E42" },
  { id: "new-mexico", name: "University of New Mexico", shortName: "UNM", primary: "#BA0C2F", secondary: "#63666A" },
  { id: "arizona-wildcats", name: "Northern Arizona University", shortName: "NAU", primary: "#003466", secondary: "#FFD200" },
  { id: "hawaii", name: "University of Hawaiʻi at Mānoa", shortName: "Hawaii", primary: "#024731", secondary: "#FFFFFF" },
  { id: "oregon-state", name: "Oregon State University", shortName: "Oregon State", primary: "#DC4405", secondary: "#000000" },
  { id: "washington-state", name: "Washington State University", shortName: "WSU", primary: "#981E32", secondary: "#5E6A71" },
  { id: "montana", name: "University of Montana", shortName: "Montana", primary: "#6C1D45", secondary: "#FFFFFF" },
  { id: "wyoming", name: "University of Wyoming", shortName: "Wyoming", primary: "#492F24", secondary: "#FFC425" },
  { id: "idaho", name: "University of Idaho", shortName: "Idaho", primary: "#FFB81C", secondary: "#000000" },
  { id: "northern-iowa", name: "University of Northern Iowa", shortName: "UNI", primary: "#4B116F", secondary: "#FFCC00" },
  { id: "iowa-state", name: "Iowa State University", shortName: "Iowa State", primary: "#C8102E", secondary: "#F1BE48" },
  { id: "kansas-state", name: "Kansas State University", shortName: "K-State", primary: "#512888", secondary: "#FFFFFF" },
  { id: "missouri-state", name: "Missouri State University", shortName: "MSU Mo", primary: "#5E0009", secondary: "#FFFFFF" },
  { id: "ball-state", name: "Ball State University", shortName: "Ball State", primary: "#BA0C2F", secondary: "#FFFFFF" },
  { id: "toledo", name: "University of Toledo", shortName: "Toledo", primary: "#003E7E", secondary: "#FFD200" },
  { id: "bowling-green", name: "Bowling Green State University", shortName: "BGSU", primary: "#4F2C1D", secondary: "#FE5000" },
  { id: "kent-state", name: "Kent State University", shortName: "Kent State", primary: "#002664", secondary: "#EAAB00" },
  { id: "miami-ohio", name: "Miami University (Ohio)", shortName: "Miami OH", primary: "#C41230", secondary: "#FFFFFF" },
  { id: "ohio", name: "Ohio University", shortName: "Ohio", primary: "#154734", secondary: "#FFFFFF" },
  { id: "marshall", name: "Marshall University", shortName: "Marshall", primary: "#00B140", secondary: "#FFFFFF" },
  { id: "east-carolina", name: "East Carolina University", shortName: "ECU", primary: "#592A8A", secondary: "#FFC72C" },
  { id: "nc-state", name: "NC State University", shortName: "NC State", primary: "#CC0000", secondary: "#000000" },
  { id: "duke-adjacent", name: "Elon University", shortName: "Elon", primary: "#73000A", secondary: "#B9975B" },
  { id: "appalachian-state", name: "Appalachian State University", shortName: "App State", primary: "#000000", secondary: "#FFCC00" },
  { id: "georgia-southern", name: "Georgia Southern University", shortName: "Georgia Southern", primary: "#041E42", secondary: "#FFFFFF" },
  { id: "georgia-state", name: "Georgia State University", shortName: "Georgia State", primary: "#0039A6", secondary: "#FFFFFF" },
  { id: "florida-atlantic", name: "Florida Atlantic University", shortName: "FAU", primary: "#003366", secondary: "#CC0000" },
  { id: "fiu", name: "Florida International University", shortName: "FIU", primary: "#081E3F", secondary: "#B6862C" },
  { id: "uab", name: "UAB", shortName: "UAB", primary: "#006341", secondary: "#CC8A00" },
  { id: "troy", name: "Troy University", shortName: "Troy", primary: "#6D0017", secondary: "#FFFFFF" },
  { id: "south-alabama", name: "University of South Alabama", shortName: "South Alabama", primary: "#00205B", secondary: "#BF0D3E" },
  { id: "charlotte", name: "UNC Charlotte", shortName: "Charlotte", primary: "#00703C", secondary: "#FFFFFF" },
  { id: "old-dominion", name: "Old Dominion University", shortName: "ODU", primary: "#003057", secondary: "#7C878E" },
  { id: "james-madison", name: "James Madison University", shortName: "JMU", primary: "#450084", secondary: "#CBB677" },
  { id: "virginia-military", name: "VMI", shortName: "VMI", primary: "#AE122A", secondary: "#FFD200" },
  { id: "richmond", name: "University of Richmond", shortName: "Richmond", primary: "#990000", secondary: "#000066" },
  { id: "william-mary", name: "William & Mary", shortName: "W&M", primary: "#115740", secondary: "#B9975B" },
  { id: "american", name: "American University", shortName: "American", primary: "#ED193D", secondary: "#004FA2" },
  { id: "george-washington", name: "George Washington University", shortName: "GW", primary: "#002654", secondary: "#E8AA4B" },
  { id: "george-mason", name: "George Mason University", shortName: "GMU", primary: "#006633", secondary: "#FFCC33" },
  { id: "virginia-commonwealth", name: "Virginia Commonwealth University", shortName: "VCU", primary: "#000000", secondary: "#FFB300" },
  { id: "temple", name: "Temple University", shortName: "Temple", primary: "#9D2235", secondary: "#FFFFFF" },
  { id: "villanova", name: "Villanova University", shortName: "Villanova", primary: "#00205B", secondary: "#FFFFFF" },
  { id: "drexel", name: "Drexel University", shortName: "Drexel", primary: "#07294D", secondary: "#FFC600" },
  { id: "lehigh", name: "Lehigh University", shortName: "Lehigh", primary: "#653819", secondary: "#FFFFFF" },
  { id: "lafayette", name: "Lafayette College", shortName: "Lafayette", primary: "#98002E", secondary: "#FFFFFF" },
  { id: "bucknell", name: "Bucknell University", shortName: "Bucknell", primary: "#003865", secondary: "#FF6600" },
  { id: "colgate", name: "Colgate University", shortName: "Colgate", primary: "#821019", secondary: "#FFFFFF" },
  { id: "syracuse-adj", name: "Siena College", shortName: "Siena", primary: "#006747", secondary: "#FFD200" },
  { id: "buffalo", name: "University at Buffalo (SUNY)", shortName: "Buffalo", primary: "#005BBB", secondary: "#FFFFFF" },
  { id: "stony-brook", name: "Stony Brook University", shortName: "Stony Brook", primary: "#990000", secondary: "#FFFFFF" },
  { id: "albany", name: "University at Albany (SUNY)", shortName: "Albany", primary: "#46166B", secondary: "#FFD200" },
  { id: "binghamton", name: "Binghamton University", shortName: "Binghamton", primary: "#005A43", secondary: "#FFFFFF" },
  { id: "umass", name: "UMass Amherst", shortName: "UMass", primary: "#881C1C", secondary: "#FFFFFF" },
  { id: "uconn", name: "University of Connecticut", shortName: "UConn", primary: "#000E2F", secondary: "#FFFFFF" },
  { id: "rhode-island", name: "University of Rhode Island", shortName: "URI", primary: "#002147", secondary: "#75B2DD" },
  { id: "new-hampshire", name: "University of New Hampshire", shortName: "UNH", primary: "#041E42", secondary: "#FFFFFF" },
  { id: "vermont", name: "University of Vermont", shortName: "UVM", primary: "#007155", secondary: "#FFD200" },
  { id: "maine", name: "University of Maine", shortName: "Maine", primary: "#003263", secondary: "#B0B7BE" },
  { id: "northeastern", name: "Northeastern University", shortName: "Northeastern", primary: "#C8102E", secondary: "#000000" },
  { id: "providence", name: "Providence College", shortName: "Providence", primary: "#000000", secondary: "#FFFFFF" },
  { id: "marquette", name: "Marquette University", shortName: "Marquette", primary: "#003366", secondary: "#FFD200" },
  { id: "depaul", name: "DePaul University", shortName: "DePaul", primary: "#005EB8", secondary: "#E4002B" },
  { id: "loyola-chicago", name: "Loyola University Chicago", shortName: "Loyola", primary: "#92003B", secondary: "#FDB913" },
  { id: "butler", name: "Butler University", shortName: "Butler", primary: "#13294B", secondary: "#FFFFFF" },
  { id: "xavier", name: "Xavier University", shortName: "Xavier", primary: "#00205B", secondary: "#FFFFFF" },
  { id: "dayton", name: "University of Dayton", shortName: "Dayton", primary: "#CE1141", secondary: "#004B8D" },
  { id: "creighton", name: "Creighton University", shortName: "Creighton", primary: "#005CA9", secondary: "#FFFFFF" },
  { id: "drake", name: "Drake University", shortName: "Drake", primary: "#004477", secondary: "#FFFFFF" },
  { id: "bradley", name: "Bradley University", shortName: "Bradley", primary: "#A50034", secondary: "#FFFFFF" },
  { id: "evansville", name: "University of Evansville", shortName: "Evansville", primary: "#52237F", secondary: "#FFFFFF" },
  { id: "belmont", name: "Belmont University", shortName: "Belmont", primary: "#00205B", secondary: "#C8102E" },
  { id: "liberty", name: "Liberty University", shortName: "Liberty", primary: "#00205B", secondary: "#C8102E" },
  { id: "appalachian", name: "Coastal Carolina University", shortName: "Coastal", primary: "#007377", secondary: "#A27752" },
  { id: "custom-campus", name: "Other / custom campus", shortName: "Other", primary: "#0B1F3A", secondary: "#004225" },
];

/** Sorted for dropdowns (custom last). */
export function universitiesForSelect(): UniversityPreset[] {
  const custom = UNIVERSITY_PRESETS.find((u) => u.id === "custom-campus");
  const rest = UNIVERSITY_PRESETS.filter((u) => u.id !== "custom-campus")
    .sort((a, b) => a.name.localeCompare(b.name));
  return custom ? [...rest, custom] : rest;
}

export function getUniversityById(id: string | null | undefined): UniversityPreset | undefined {
  if (!id) return undefined;
  return UNIVERSITY_PRESETS.find((u) => u.id === id);
}
